/************ Add: Sequences ***************/

/* Autogenerated Sequences */

CREATE SEQUENCE public.role_id_role_seq INCREMENT BY 1 START 1;
COMMENT ON SEQUENCE public.role_id_role_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE public.users_id_users_seq INCREMENT BY 1 START 1;
COMMENT ON SEQUENCE public.users_id_users_seq IS 'DbWrench Autogenerated Sequence.';




/************ Update: Tables ***************/

/******************** Add Table: public.role ************************/

/* Build Table Structure */
CREATE TABLE public.role
(
	id_role INTEGER DEFAULT nextval('public.role_id_role_seq'::regclass) NOT NULL,
	tipo VARCHAR(25) NULL
);

/* Add Primary Key */
ALTER TABLE public.role ADD CONSTRAINT pkrole
	PRIMARY KEY (id_role);


/******************** Add Table: public.users ************************/

/* Build Table Structure */
CREATE TABLE public.users
(
	id_users INTEGER DEFAULT nextval('public.users_id_users_seq'::regclass) NOT NULL,
	email VARCHAR(25) NULL,
	password VARCHAR(255) NULL,
	role_id INTEGER NOT NULL
);

/* Add Primary Key */
ALTER TABLE public.users ADD CONSTRAINT pkusers
	PRIMARY KEY (id_users);





/************ Add Foreign Keys ***************/

/* Add Foreign Key: fk_users_role */
ALTER TABLE public.users ADD CONSTRAINT fk_users_role
	FOREIGN KEY (role_id) REFERENCES public.role (id_role)
	ON UPDATE NO ACTION ON DELETE NO ACTION;